
# PIAIC Q2 CLASS 2

In [1]:
#numpy by default float hta hai

import numpy as np

arr2d = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]])
print(arr2d.ndim)
arr2d[2:4,1:5] #slice from 0

2


array([[0, 6, 2, 5],
       [6, 1, 5, 3]])

In [2]:
arr = np.arange(1,37).reshape(6,6)
print(arr)
arr.ndim

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


2

In [3]:
arr[1:5 , ]
#or
arr[1:5 , 0:6]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [4]:
#only want 18 and 24
#2d and 1d dono hai to it depends on u k ap kia chahte h 1d ya 2d ,slicing se 2d aega or normal se 1d
print((arr[2:4 , 5:6]).ndim)
print(arr[2:4 , 5:6])
#or
print((arr[2:4 , 5].ndim))
print(arr[2:4 , 5])
#or
print(arr[2:4 , -1].ndim)
print(arr[2:4 , -1])

2
[[18]
 [24]]
1
[18 24]
1
[18 24]


In [5]:
arr[2:4,2:5] 
#arr[row,column]
#column k liye khai chor skte likkn row k liye nhi
# arr[,2] --> error
arr[ : , 2]

array([ 3,  9, 15, 21, 27, 33])

In [6]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [7]:
#for column step
print(arr[:,::-2])
print()
print(arr[:,::2])
print()
print(arr[::2,::2])
print()
#for rows step
print(arr[::2,:])

[[ 6  4  2]
 [12 10  8]
 [18 16 14]
 [24 22 20]
 [30 28 26]
 [36 34 32]]

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]
 [25 27 29]
 [31 33 35]]

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]

[[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]
 [25 26 27 28 29 30]]


In [8]:
arr[0:5:2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

# Boolean indexing

In [9]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [10]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [11]:
data = np.random.randn(7,4)
#data = np.random.randn(shape---> rows,column)
data

array([[-0.11765737, -1.71350089, -0.38859411, -0.52006696],
       [ 0.32507283, -0.96631307,  0.27370971,  1.4926988 ],
       [-0.11722135,  2.53778979, -0.48174114, -0.0596889 ],
       [-1.60964624, -0.27307077, -0.86007454,  0.26475455],
       [ 0.61424391,  1.15099899,  0.67889266, -0.09408592],
       [ 0.04063406,  1.67716572,  2.39399877, -0.43184502],
       [-0.87322262,  0.05296608,  2.24059419, -2.86372762]])

In [12]:
#if only want to check k 1 se bara kahan kahan pr hai 
data > 1

array([[False, False, False, False],
       [False, False, False,  True],
       [False,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True,  True, False],
       [False, False,  True, False]])

In [13]:
#if want values then data k andar data rkhenge....mtlb ek frame mein rkhenge
data[data > 1]

array([1.4926988 , 2.53778979, 1.15099899, 1.67716572, 2.39399877,
       2.24059419])

In [14]:
data[names == "Bob"]
#yahha ye hoga k jahan jahan bob hoga wo wali rows ajaengi


array([[-0.11765737, -1.71350089, -0.38859411, -0.52006696],
       [-1.60964624, -0.27307077, -0.86007454,  0.26475455]])

In [15]:
# data[True, False, False,  True, False, False, False ] ---> ye ans nh dega to hmein boolean form deni hogi
bol = np.array([True, False, False,  True, False, False, False ],dtype = "bool")
data[bol]

array([[-0.11765737, -1.71350089, -0.38859411, -0.52006696],
       [-1.60964624, -0.27307077, -0.86007454,  0.26475455]])

In [16]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [17]:
data[names != "Bob"]

array([[ 0.32507283, -0.96631307,  0.27370971,  1.4926988 ],
       [-0.11722135,  2.53778979, -0.48174114, -0.0596889 ],
       [ 0.61424391,  1.15099899,  0.67889266, -0.09408592],
       [ 0.04063406,  1.67716572,  2.39399877, -0.43184502],
       [-0.87322262,  0.05296608,  2.24059419, -2.86372762]])

In [18]:
cond = names != "Bob"

In [19]:
data[cond]

array([[ 0.32507283, -0.96631307,  0.27370971,  1.4926988 ],
       [-0.11722135,  2.53778979, -0.48174114, -0.0596889 ],
       [ 0.61424391,  1.15099899,  0.67889266, -0.09408592],
       [ 0.04063406,  1.67716572,  2.39399877, -0.43184502],
       [-0.87322262,  0.05296608,  2.24059419, -2.86372762]])

In [20]:
data[~cond] # ~ (not)

array([[-0.11765737, -1.71350089, -0.38859411, -0.52006696],
       [-1.60964624, -0.27307077, -0.86007454,  0.26475455]])

In [21]:
data

array([[-0.11765737, -1.71350089, -0.38859411, -0.52006696],
       [ 0.32507283, -0.96631307,  0.27370971,  1.4926988 ],
       [-0.11722135,  2.53778979, -0.48174114, -0.0596889 ],
       [-1.60964624, -0.27307077, -0.86007454,  0.26475455],
       [ 0.61424391,  1.15099899,  0.67889266, -0.09408592],
       [ 0.04063406,  1.67716572,  2.39399877, -0.43184502],
       [-0.87322262,  0.05296608,  2.24059419, -2.86372762]])

In [22]:
data[~cond,3]

array([-0.52006696,  0.26475455])

In [23]:
data[~cond,1:3]

array([[-1.71350089, -0.38859411],
       [-0.27307077, -0.86007454]])

In [24]:
#complete
data = np.arange(28).reshape(7,4)
print(data)
print(cond)
data[cond,1:3]  #column dedia 1:3


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [25]:
#complete with negation
data = np.arange(28).reshape(7,4)
print(data)
print(~cond)
data[~cond,1:3]  #column dedia 1:3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[ True False False  True False False False]


array([[ 1,  2],
       [13, 14]])

In [26]:
#in numpy and or kaam nhi krta to sign wala hta hai --> and k liye & or k liye pipe
cond = (names == "Bob") & (names == "Joe")
cond

array([False, False, False, False, False, False, False])

In [27]:
#in numpy and or kaam nhi krta to sign wala hta hai ---> and k liye& or k liye pipe
cond = (names == "Bob") | (names == "Joe")
cond

array([ True,  True, False,  True, False,  True,  True])

In [28]:
data[cond]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

# Fancy indexing

In [29]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

In [30]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [31]:
#slicing mein hm bs ek do nikaal rhe the ab jo chahe wo nikaal skte

In [32]:
arr[3]

array([3., 3., 3., 3.])

In [33]:
arr[[4,0,1,7]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [34]:
# arr[[4,7,1,7],[2,5,7]] --- > error because column out of range 4 se ziada h

In [35]:
arr[[4,2,3,4],[0,1,2,3]]
#it makes an order pair like [(4,0),(2,1),(3,2),(4,3)]

array([4., 2., 3., 4.])

In [36]:
arr = np.arange(32).reshape(8,4)
print(arr)

#for 2d

arr[[1,5,7,2]][:,[0,3,1,2]]
# arr[[......]][:] -- > is colon ka mtlb k sb sbk sath pair bnaege mtlb k 1 0312 k sath phr 5.....

# 1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[0,3,1,2]
# (1,0)(1,3)(1,1)(!,2)(5,0)()()()()()......

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [37]:
#transpose
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [38]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [39]:
#from book all 

In [40]:
arr.sort()
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [41]:
#set
lst = [2,1,1,3,4,6,5,6,3]
set(lst)

{1, 2, 3, 4, 5, 6}

In [42]:
#unique
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [43]:
#concatenate

# 0 axis pr izafa rows mein ata
#1 axis pr izafa column mein ata

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1,arr2], axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
np.concatenate([arr1,arr2], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [45]:
#stack

#vstack
#hstack

np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [47]:
arr = np.arange(36).reshape(6,6)
arr
#5 ka bnta nh

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [48]:
#split
#vsplit -- > row wise krega vertical mein
np.vsplit(arr,3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [49]:
#hsplit -- > column wise krega horizontal mein
np.hsplit(arr,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [50]:
#repeat

In [51]:
#tiles ---> axis lga k dekhna