# PIAIC Q2 CLASS 3

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3]])  #ek row 3 column
print(x.shape)
y = np.array([[4]
              ,[5]]) #2 row ek column
print(y.shape)

(1, 3)
(2, 1)


In [3]:
a , b = np.broadcast_arrays(x,y)

In [4]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
b

array([[4, 4, 4],
       [5, 5, 5]])

In [6]:
a + b

array([[5, 6, 7],
       [6, 7, 8]])

In [7]:
# x = np.array([[1,2,3],[1,2,3],[1,2,3]])  #ek row 3 column
# print(x.shape)
# y = np.array([[4]
#               ,[5]]) #2 row ek column
# print(y.shape)


#"""Error"""

# PANDAS

In [8]:
#alias
#standard is pd

In [9]:
import pandas as pd

### Pandas Data Structures Series DafaFrame ###
##### Series #####

In [10]:
s1 = pd.Series([11,22,33,44,55,66,77,88,99,111])

In [11]:
s1 #pandas series object

0     11
1     22
2     33
3     44
4     55
5     66
6     77
7     88
8     99
9    111
dtype: int64

In [12]:
#provides index
#index (0-9 default index given ny series object)

In [13]:
s1[9] # get values by using  index
#accessing values by index

111

In [14]:
# s1[2,4,5,9,0] #key error

In [15]:
s1[0:10:2] #slicing

0    11
2    33
4    55
6    77
8    99
dtype: int64

### same as fancy indexing in numpy ###

In [16]:
#not take multiple indexing so fany index
s1[[0,1,2,3,4]] #accessing multiple values

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [17]:
###replace ###

s1[5] = 555 #modifying the value in s1 series
s1[1,2,3,4] = [3,4,5,6] #direct
s1[[1,2,3,4]] = [3,4,5,6] #fancy
s1

0     11
1      3
2      4
3      5
4      6
5    555
6     77
7     88
8     99
9    111
dtype: int64

In [18]:
###delete ###
del s1[5]
s1
###multiple delete###

0     11
1      3
2      4
3      5
4      6
6     77
7     88
8     99
9    111
dtype: int64

In [19]:
s1[99] = 999 #insert in a series with a new index
# s1?[[22,33]] = [2,3]
s1

0      11
1       3
2       4
3       5
4       6
6      77
7      88
8      99
9     111
99    999
dtype: int64

In [20]:
s2 = pd.Series([10,20,30,40], index = ["orange","apple","bananas","kiwi"]) # index apni marzi ka rkhskte like dict

In [21]:
s2

orange     10
apple      20
bananas    30
kiwi       40
dtype: int64

In [22]:
s2.index

Index(['orange', 'apple', 'bananas', 'kiwi'], dtype='object')

In [23]:
s2.values

array([10, 20, 30, 40], dtype=int64)

In [24]:
ourindex = ["orange","apple","bananas","kiwi"]
s2 = pd.Series([10,20,30,40] , index = ourindex)
s2

orange     10
apple      20
bananas    30
kiwi       40
dtype: int64

In [25]:
s2 > 30 #only true false

orange     False
apple      False
bananas    False
kiwi        True
dtype: bool

In [26]:
s2 [s2 > 30] #to get  value as well # jo data hai usk andar hi uski query chalai jae

kiwi    40
dtype: int64

In [27]:
"peech" in s2

False

In [28]:
"orange" in s2

True


# Creating a series by using a dictionary

In [29]:
sdata = {"Ohio" : 3500, "Texas" : 7100, "Oregon" : 16000,"Utah" : 5000}
data = pd.Series(sdata)
data

Ohio       3500
Texas      7100
Oregon    16000
Utah       5000
dtype: int64

In [30]:
states = ["California", "Ohio", "Oregon","Texas"]
data1 = pd.Series(sdata, index = states)
data1
#california missing to not a number NaN

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas          7100.0
dtype: float64

In [31]:
data1["California"] = 40000

In [32]:
data1

California    40000.0
Ohio           3500.0
Oregon        16000.0
Texas          7100.0
dtype: float64

In [33]:
data1.isnull()

California    False
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
data1.notnull()

California    True
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [35]:
data1["California"] = 55000

In [36]:
data1

California    55000.0
Ohio           3500.0
Oregon        16000.0
Texas          7100.0
dtype: float64

# Dataframes

In [37]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],     
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df1 = pd.DataFrame(data)
df1
#header bnjaega

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [38]:
# df1["pop"]
#"""or"""
df1.pop
# df1.year

<bound method NDFrame.pop of     state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2>

In [39]:
no = [1,2,3,4]
data = {"Name" : ["Salman", "Khadija", "Javeria"],
        "Relation" : ["Brother","Sister","Myself"],
        "Fields" : ["EE","EE","CIS"]}
data1 =  pd.DataFrame(data)
data1
#check how to change index

Name Relation Fields
0   Salman  Brother     EE
1  Khadija   Sister     EE
2  Javeria   Myself    CIS

In [40]:
type(df1)

pandas.core.frame.DataFrame

In [41]:
df1.shape

(6, 3)

In [42]:
df1[["pop","year"]]

pop  year
0  1.5  2000
1  1.7  2001
2  3.6  2002
3  2.4  2001
4  2.9  2002
5  3.2  2003

In [43]:
del df1["pop"]

In [44]:
df1

state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002
5  Nevada  2003

In [45]:
df1["debt"] = 1000
df1

state  year  debt
0    Ohio  2000  1000
1    Ohio  2001  1000
2    Ohio  2002  1000
3  Nevada  2001  1000
4  Nevada  2002  1000
5  Nevada  2003  1000

In [46]:
#to insert
df1["debt"] = [100,200,300,400,500,600]
df1
#single value fit in whole column

state  year  debt
0    Ohio  2000   100
1    Ohio  2001   200
2    Ohio  2002   300
3  Nevada  2001   400
4  Nevada  2002   500
5  Nevada  2003   600

In [47]:
df1["debt"] = range(6)
df1

state  year  debt
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4
5  Nevada  2003     5

In [48]:
df1["debt"] = df1["state"]
df1

state  year    debt
0    Ohio  2000    Ohio
1    Ohio  2001    Ohio
2    Ohio  2002    Ohio
3  Nevada  2001  Nevada
4  Nevada  2002  Nevada
5  Nevada  2003  Nevada

In [49]:
dic = {
    "Ai for everyone" : [89,96,92],
    "Python quiz 1" : [97,94,96],
    "Python quiz 2" : [99,93,96],
}

df = pd.DataFrame(dic, index = ["Javeria","Khadija","Salman"])
df


Ai for everyone  Python quiz 1  Python quiz 2
Javeria               89             97             99
Khadija               96             94             93
Salman                92             96             96

In [50]:
df["Total"] = ((df["Ai for everyone"] + df["Python quiz 1"] + df["Python quiz 2"]) / 3).round()
df["Percentage"] = (((df["Ai for everyone"] + df["Python quiz 1"] + df["Python quiz 2"]) / 300) * 100)
df

Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage
Javeria               89             97             99   95.0   95.000000
Khadija               96             94             93   94.0   94.333333
Salman                92             96             96   95.0   94.666667

In [51]:
df["Status"] = df["Total"] > 95
# df["Status"] = "Pass"
df


Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage  \
Javeria               89             97             99   95.0   95.000000   
Khadija               96             94             93   94.0   94.333333   
Salman                92             96             96   95.0   94.666667   

         Status  
Javeria   False  
Khadija   False  
Salman    False

In [52]:
df['status']=["Pass" if a >= 33 and p1 >= 33 and p2 >= 33 else "Fails"
              for a,p1,p2 in zip(df['Ai for everyone'],df['Python quiz 1'],df['Python quiz 2'])]
df

Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage  \
Javeria               89             97             99   95.0   95.000000   
Khadija               96             94             93   94.0   94.333333   
Salman                92             96             96   95.0   94.666667   

         Status status  
Javeria   False   Pass  
Khadija   False   Pass  
Salman    False   Pass

In [53]:
numbers= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
evenArr = []
oddArr = []
for num in numbers:
    if num%2==0:
        evenArr.append(num)
    else:
        oddArr.append(num)
print("Evens>>", evenArr)
print("Odds>>>", oddArr)

Evens>> [2, 4, 6, 8, 10, 12, 14]
Odds>>> [1, 3, 5, 7, 9, 11, 13, 15]


In [54]:
[i for i in range(16) if i % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14]

In [55]:
a = list(range(5))
b = list(range(6,11))

In [56]:
a

[0, 1, 2, 3, 4]

In [57]:
b

[6, 7, 8, 9, 10]

In [58]:
c = zip(a,b)
for i in c:
    print(i)

(0, 6)
(1, 7)
(2, 8)
(3, 9)
(4, 10)


In [59]:
# df.Ai for everyone --- > error so use
df["Ai for everyone"]

Javeria    89
Khadija    96
Salman     92
Name: Ai for everyone, dtype: int64

In [60]:
df.head() # if want less rows
#default 5 rows

Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage  \
Javeria               89             97             99   95.0   95.000000   
Khadija               96             94             93   94.0   94.333333   
Salman                92             96             96   95.0   94.666667   

         Status status  
Javeria   False   Pass  
Khadija   False   Pass  
Salman    False   Pass

In [61]:
df.head(2)

Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage  \
Javeria               89             97             99   95.0   95.000000   
Khadija               96             94             93   94.0   94.333333   

         Status status  
Javeria   False   Pass  
Khadija   False   Pass

In [62]:
df.tail(1) #last se rows leta hai

Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage  \
Salman               92             96             96   95.0   94.666667   

        Status status  
Salman   False   Pass

In [63]:
df.loc["Javeria":"Salman"]

Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage  \
Javeria               89             97             99   95.0   95.000000   
Khadija               96             94             93   94.0   94.333333   
Salman                92             96             96   95.0   94.666667   

         Status status  
Javeria   False   Pass  
Khadija   False   Pass  
Salman    False   Pass

In [64]:
df.iloc[0:2]

Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage  \
Javeria               89             97             99   95.0   95.000000   
Khadija               96             94             93   94.0   94.333333   

         Status status  
Javeria   False   Pass  
Khadija   False   Pass

In [65]:
df.iloc[2::-1]

Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage  \
Salman                92             96             96   95.0   94.666667   
Khadija               96             94             93   94.0   94.333333   
Javeria               89             97             99   95.0   95.000000   

         Status status  
Salman    False   Pass  
Khadija   False   Pass  
Javeria   False   Pass

In [66]:
#loc or iloc mein farq ye hai k lloc mein end index bhi include hota hai likn iloc mein last index include nhi hota ...
#loc yani location and iloc yani index location

In [67]:
df.loc["MI"] = [1,2,3,4,5,6,7] # row add hogi or values utni deni hogi lazmi jitne columns hain
df

Ai for everyone  Python quiz 1  Python quiz 2  Total  Percentage  \
Javeria               89             97             99   95.0   95.000000   
Khadija               96             94             93   94.0   94.333333   
Salman                92             96             96   95.0   94.666667   
MI                     1              2              3    4.0    5.000000   

         Status status  
Javeria       0   Pass  
Khadija       0   Pass  
Salman        0   Pass  
MI            6      7