# Revision of class 1

In [1]:
import numpy as np

arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
# print(arr3d)
print(arr3d[0][2]) #bcoz 3d array hai to first 2d denge pphr 1d ...qk sbse ziada dimension hai 3d to usk low wali pehle read krega to 2d phr 1d

[7 8 9]


In [2]:
arr4d = np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
# print(arr3d)
print(arr4d[0][0][2])

arr4d.ndim

[7 8 9]


4

In [3]:
# shape mein ye hta hai k agr 2d hai to 2 axis dikhaega or 3d hai to 3 axis dikhaega

In [4]:
arr3d = np.array([[[100,200,300],[400,500,600],[700,800,900]],[[1,2,3],[4,5,6],[7,8,9]]])
arr3d.ndim

3

In [5]:
arr3d[1][1]

array([4, 5, 6])

In [6]:
arr3d[1][1][0]

4

In [7]:
arr3d[1,1,0]

4

In [8]:
arr3d[0,0:2,1:3]# pehle slice 2d k andar khare hogye phr 2 roes chahye #arrr3d[2d,rows,column]

array([[200, 300],
       [500, 600]])